lessons: lessons-novo.yaml
db: data/novo.sqlite3
access-log: log/access-novo.log
error-log: log/error-novo.log
static-dir: ../../MULLE/muste-ajax/static # this path has to be set properly
port: 8080
users:
  - name: guest
    password: guest
    enabled: yes
